version: '3'
networks:
    dev:
services:
    mysql:
        image: mysql:8.0
        container_name: vallourec_mysql
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: password_01
        networks:
            - dev
        restart: always
        ports:
            - 3306:3306
        expose:
            - 3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: vallourec_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8090:80
        links:
            - mysql
        networks:
            - dev
        depends_on:
            - mysql
        restart: always

    vallourec_nodejs:
        build: ./vallourec_nodejs
        container_name: vallourec_nodejs
        ports:
            - 8081:8081
        networks:
            - dev
        depends_on:
            - mysql
        restart: always
        command: >
            sh -c "/wait && npm start"
        environment:
          - WAIT_HOSTS=mysql:3306
          - WAIT_HOSTS_TIMEOUT=10
          - WAIT_SLEEP_INTERVAL=10
          - WAIT_HOST_CONNECT_TIMEOUT=10

    vallourec_symfony:
        build: ./vallourec_symfony
        container_name: vallourec_symfony
        ports:
            - 8001:8001
        depends_on:
            - mysql
            - vallourec_nodejs
            # - composer_installation
        networks:
            - dev
        restart: always
        environment:
          - WAIT_HOSTS=vallourec_nodejs:8081
          - WAIT_HOSTS_TIMEOUT=10
          - WAIT_SLEEP_INTERVAL=10
          - WAIT_HOST_CONNECT_TIMEOUT=10
        command: >
            bash -c "/wait 
            && symfony local:server:stop 
            && symfony server:start --port=8001"

    vallourec_angular:
        build: ./vallourec_angular
        container_name: vallourec_angular
        ports:
            - 4201:4200
        networks:
            - dev
        depends_on:
        depends_on:
            - vallourec_symfony
        restart: always
        command: >
            sh -c "/wait && npm run start-dockerized"
        environment:
          - WAIT_HOSTS=vallourec_symfony:8001
          - WAIT_HOSTS_TIMEOUT=10
          - WAIT_SLEEP_INTERVAL=10
          - WAIT_HOST_CONNECT_TIMEOUT=10
